### ISSUE TITLE
Implement Secure Gossip Channel for Public Key Distribution in Distributed Network

### ISSUE THREAD

**Issue by teslashibe** [masa-finance/masa-oracle#149]
### Objective:
To enhance the security and integrity of our distributed network, we aim to implement a secure gossip channel for the distribution of the public key of the node designated as the key writer. This approach will ensure that only the authorized node can perform write operations to the shared database, leveraging cryptographic verification for authentication.

### Background:
Our current setup involves a distributed network where nodes communicate using libp2p. We have identified the need to restrict write access to the shared database to a single node that we control. To achieve this, we plan to use cryptographic keys for node authentication, where the writer node signs write requests with its private key. Other nodes in the network will verify these requests using the writer node's public key.

### Implementation Steps:
1. **Generate Cryptographic Key Pair for the Writer Node:**
   - Use libp2p's cryptographic functionalities to generate a unique key pair for the writer node.
   - Example code snippet:

2. **Secure Gossip Channel for Public Key Distribution:**
   - Implement a gossip protocol over libp2p to securely distribute the writer node's public key to all nodes in the network.
   - Ensure the gossip protocol is secure and resistant to tampering or unauthorized disclosure of the public key.

3. **Modify Access Control Logic:**
   - Adjust the `Verifer` function in `access_control.go` to verify the signature of write requests using the distributed public key.
   - Example modification:

4. **Sign Write Requests in the Writer Node:**
   - Ensure the writer node signs its write requests with its private key before sending them to the network.
   - Example code snippet:

5. **Implementing Create CacheSyncing Methodology for this task**
- Sync to resolver cache will handle this request.

### Security Considerations:
- The gossip protocol must ensure the integrity and authenticity of the public key during distribution.
- Nodes should verify the source of the public key to prevent man-in-the-middle attacks.
- Regularly rotate the cryptographic keys to mitigate the risk of key compromise.

**Comment by teslashibe** [comment]
This may not be the right way to go

**Comment by jdutchak** [comment]
Added 5. **Implementing Create CacheSyncing Methodology for this task**
- Sync to resolver cache will handle this request.

**Comment by jdutchak** [comment]
included in Issue-148 no merge needed
