### ISSUE TITLE
Refactor Configuration Management by introducing a config package

### ISSUE THREAD

**Issue by restevens402** [masa-finance/masa-oracle#154]
#### Summary

The cmd/masa-node directory has become overly complex due to the extensive configuration code. To streamline the application structure and improve maintainability, we propose introducing a config package within the pkg directory. This package will centralize configuration management and ensure a clear separation of concerns. Additionally, it will house the constants.go file to consolidate constants used across the application.

#### Goals

- Simplify cmd/masa-node Directory: Reduce the complexity of the cmd/masa-node directory by moving configuration-related code to a dedicated package.

- Centralize Configuration Management: Create a config package that serves as the single source of truth for configuration management.

- Avoid Circular Dependencies: Ensure the config package does not use any other internal packages to prevent circular dependencies.

- Refactor constants.go: Move constants.go to the config package to centralize constants definitions.

#### Proposed Changes

1. Create config Package: Establish a new config package within the pkg directory for configuration-related logic.

2. Move and Update constants.go: Relocate constants.go to the config package and update any package references accordingly.

3. Define Configuration Structs: Implement structs in config.go within the config package to represent the application's configuration settings.

4. Implement Configuration Initialization: Develop a LoadConfig function in the config package to initialize and return configuration settings from various sources (e.g., environment variables, flags).

5. Refactor cli.go: Update cli.go to utilize the config package for loading configuration settings, replacing the existing initialization logic.

6. Ensure No Internal Dependencies: Verify that the config package only relies on external libraries and the Go standard library, avoiding imports of other internal packages.

#### Testing and Validation

- Thoroughly test the application post-refactoring to ensure that configuration settings are correctly loaded and the application functions as expected.

- Validate that the config package operates independently without creating circular dependencies within the application.

#### Additional Notes

- This restructuring aims to enhance the application's maintainability and scalability by clearly separating configuration management into its dedicated package.

**Comment by teslashibe** [comment]
@restevens402 nice!

**Comment by teslashibe** [comment]
@restevens402 closing - merged to dev
