### ISSUE TITLE
Implement Singleton KeyManager for Cryptographic Operations

### ISSUE THREAD

**Issue by restevens402** [masa-finance/masa-oracle#155]
#### Summary

We need to implement a singleton KeyManager within our application to centralize the management of cryptographic entities such as private and public keys. This singleton will ensure that there is only one instance of the key manager throughout the application, providing a consistent access point for cryptographic operations and data.

#### Goals

- Centralize Cryptographic Management: Create a KeyManager struct that holds all cryptographic entities used in the application (e.g., Libp2p keys, ECDSA keys).

- Implement Singleton Pattern: Ensure KeyManager is accessible as a singleton, guaranteeing that only one instance exists throughout the application lifecycle.

- Thread-Safe Initialization: Use sync.Once to ensure that the KeyManager instance is initialized in a thread-safe manner.

- Key Initialization and Management: Implement logic within KeyManager to load or generate necessary cryptographic keys upon initialization.

#### Implementation Details

- KeyManager Struct: Define a KeyManager struct with attributes for each type of cryptographic entity required by the application, such as Libp2pPrivKey, Libp2pPubKey, EcdsaPrivKey, and EcdsaPubKey.

- Singleton Access: Utilize a combination of a private instance variable (keyManagerInstance) and a public GetInstance method, with sync.Once ensuring thread-safe initialization.

- Initialization Logic: The initializeKeys method within KeyManager will handle the loading or generation of cryptographic keys. This method needs to be adjusted to include the actual logic for managing these keys.

- Logging and Error Handling: Implement appropriate logging and error handling for the initialization process and key management operations.

#### Usage

Developers can access the KeyManager instance from anywhere in the application using:

```
keyManager := crypto.GetInstance()
```

This instance provides centralized access to cryptographic keys and operations, ensuring consistency and security across the application.

#### Additional Notes

- The implementation should consider security best practices for key management, including secure storage and handling of private keys.

- Further methods for key usage and management may be added to KeyManager as needed by the application.

**Comment by teslashibe** [comment]
Closed - merged to dev @restevens402
