### ISSUE TITLE
Twitter Data Scraping Node Integration

### ISSUE THREAD

**Issue by teslashibe** [masa-finance/masa-oracle#164]
### Summary
Implement the `ScrapeTweetsByQuery` function within the Masa Oracle Node to enable efficient scraping of Twitter data based on user queries.

### Tasks
1. Integrate the `ScrapeTweetsByQuery` function from `pkg/twitter/tweets_by_query.go` into the Oracle Node's workflow.
2. Ensure compatibility with various search modes and filters to enable comprehensive data retrieval.
3. Develop a method for the Oracle Node to initialize itself to serve scraped Twitter to a node that requests it.

### Dependencies
- Twitter Scraper library.
- Existing Oracle Node infrastructure.

### Acceptance Criteria
- The Oracle Node can scrape Twitter data based on specific queries.
- Scraped data is correctly processed and temporarily stored for further analysis.

**Comment by jdutchak** [comment]
Can close this
