### ISSUE TITLE
Claude Sentiment Analysis Integration & Node API

### ISSUE THREAD

**Issue by teslashibe** [masa-finance/masa-oracle#166]
### Summary
Integrate the `AnalyzeSentiment` function from `claude.go` into the Masa Oracle Node, enabling sentiment analysis of scraped Twitter data through an API (we may want to protect this endpoint so only Masa can access it from a user facing front end in our first version)

### Tasks
1. Requests can be accepted from a chat interface through an API endpoint on the node that get passed to the Decentralized Twitter Scraper for processing and return. There will be latency here so the front end should indicate to the user that the request is processing as the result may take some time to return - this is acceptable in this first version. We are not optimizing for response time. 
2.` Open Question?`:Do we want to store the response into a database of tweets with the tweetID as the PK so we replicate the content of TW over time? 
3. Modify the `AnalyzeSentiment` function to work with data scraped by the decentralized network of nodes that scrape Twitter data as detailed in https://github.com/masa-finance/masa-oracle/issues/165.
4. Ensure the function can handle large volumes of data and return analysis results in a timely manner. Keep temperature of the model low `=0 ` so we keep the response constrained. 
5. Integrate the sentiment analysis results into an API endpoint on the node, making them available for the chat interface.

### Dependencies
- Claude API for sentiment analysis.
- Modifications to the `AnalyzeSentiment` function to support decentralized data.

### Acceptance Criteria
- The Oracle Node can analyze the sentiment of scraped Twitter data using the Claude model.
- Sentiment analysis results are accurately processed and made available for display in the chat interface.

**Comment by jdutchak** [comment]
Can close this
