### ISSUE TITLE
Implementing Web Scraping Sentiment Analysis

### ISSUE THREAD

**Issue by jdutchak** [masa-finance/masa-oracle#187]
### Title
Implementing Web Scraping Sentiment Analysis Using Colly in Masa Oracle

#### Overview

We are planning to enhance the sentiment analysis feature of the Masa Oracle by incorporating web scraping capabilities using the Colly library. This approach will allow us to fetch tweets more efficiently and robustly, providing a solid foundation for our sentiment analysis feature.

#### Goals

- Integrate Colly for web scraping in the sentiment analysis process.
- Ensure the new implementation respects rate limits and sites terms of service.
- Maintain or improve the current performance and accuracy of sentiment analysis.

#### Implementation Plan

1. Library Integration: Replace the current scraping mechanism with Colly. This involves modifying the llmbridge package where tweets are fetched.

```go
   import (
       "github.com/gocolly/colly"
       // other imports
   )
```

2. Scraping Logic: Develop a new function in sentiment_web.go to scrape tweets using Colly. This function will target specific elements on the web pages to extract tweet data.

```go
   func FetchPageWithColly(query string, count int) ([]*Links, error) {
       // Implementation using Colly
   }
```

3. Integration with Sentiment Analysis: Ensure the fetched site are correctly formatted and passed to the AnalyzeSentiment function for sentiment analysis.

4. Testing and Validation: Rigorously test the new implementation to ensure it meets our performance and accuracy benchmarks. This includes unit tests and integration tests with the sentiment analysis feature.

5. Documentation: Update the docs/LLM.md to reflect the changes in the web fetching process and any new configurations or limitations introduced by using Colly.

#### Considerations

- Rate Limiting: Implement rate limiting in our Colly configuration to avoid hitting a websites rate limits or causing any service disruptions.

- Error Handling: Robust error handling to manage scenarios where websites cannot be fetched due to network issues, changes in HTML structure, etc.

- Compliance: Ensure our use of Colly complies with the websites terms of service to avoid any legal issues.

#### Timeline

This enhancement to the Masa Oracle's sentiment analysis feature will leverage the Colly library for more efficient and reliable site fetching. We anticipate this change will improve the overall performance and scalability of our sentiment analysis capabilities.

**Comment by teslashibe** [comment]
@jdutchak this got completed right? Do we need to QA this with the current changes we have made to the oracle to make sure it all works still?
