### ISSUE TITLE
Stand-up S3 for Incoming Oracle Data

### ISSUE THREAD

**Issue by theMultitude** [masa-finance/masa-oracle#250]
Allocate S3 bucket to act as a repository for incoming oracle data (from Firehose via the API gateway).

For naming conventions we can start with Raw_Oracle_Threads in whatever style aligns with how you've been naming previously.

**Comment by teslashibe** [comment]
@theMultitude can you point me in the direction of the shape of the json body that is to be posted to he endpoint? Or does it take any shape that is fired to it?

**Comment by teslashibe** [comment]
@theMultitude - I found it: https://github.com/masa-finance/masa-oracle-infra/issues/70
