### ISSUE TITLE
Discord Scraper P0

### ISSUE THREAD

**Issue by nolanjacobson** [masa-finance/masa-oracle#252]
2. **Discord Profile and Guild Membership Scraper**
    - Uncover valuable insights from Discord communities with our Discord Profile and Guild Membership Scraper. Extract comprehensive user profile data, including usernames, roles, and guild memberships. Leverage this data to enhance your AI models, perform user analytics, and gain a deeper understanding of Discord communities.
 
## Acceptance  criteria 

- [ ] Scrape discord profile 
- [ ] Scrape guild memberships of profile
- [ ] OAuth2 - out of scope

**Comment by teslashibe** [comment]
@nolanjacobson let me write some user stories. Maybe we can chat for 15mins
