### ISSUE TITLE
Malformed request body example in Swagger docs for Chat Completion endpoint

### ISSUE THREAD

**Issue by teslashibe** [masa-finance/masa-oracle#276]
Description:
The request body example shown in the Swagger documentation for the Chat Completion API endpoint appears to be malformed JSON. Specifically:

- The opening and closing curly braces are missing for the JSON object
- The "Content-Type" header is included directly in the request body instead of in the headers section
- The "text" field is missing a value

This looks to be an issue with how the Swagger docs are being automatically generated from the API definition.

Steps to Reproduce:
1. Open the Swagger documentation page 
2. Navigate to the Chat Completion endpoint
3. Expand the example request body

Expected Result:
The example request body should be properly formatted JSON, with the Content-Type specified in the headers section.

Actual Result:
The request body is malformed and would result in an invalid API request.

Priority: Medium

Assignee: Bob Stevens

@restevens402  - Could you please take a look at this when you have a chance? It seems like it should be a straightforward fix to update the API definition file to generate a correct example in the Swagger UI. Let me know if you have any questions. Thanks!

**Comment by restevens402** [comment]
I have updated the swagger docs and opened a PR which is associated with this ticket.
