### ISSUE TITLE
Node shutting down when user curl the request through another terminal on the same node machine

### ISSUE THREAD

**Issue by Luka-Loncar** [masa-finance/masa-oracle#302]
Link to bug report in Slack: https://masafinance.slack.com/archives/C073K1YP8CR/p1717078141125279

![Image](https://github.com/masa-finance/masa-oracle/assets/56362462/6f38ee66-692b-4a60-9744-9a8768c41c2b)

This is also happening through the swagger. The only thing I did before this started happening was at the GCP instance level (reserve and assign a static IP, create a firewall rule for open ingress). The curl command was a simple cope paste from the swagger itself.

**Comment by teslashibe** [comment]
@restevens402 @jdutchak @Luka-Loncar  closing this because its solved
