### ISSUE TITLE
Worker storage metrics

### ISSUE THREAD

**Issue by Luka-Loncar** [masa-finance/masa-oracle#314]
Issue: Implementation of Worker Storage Metrics

Description

This issue focuses on enhancing the storage metrics for workers in the system by implementing the following features:

1. Store CID in DHT for Availability:
- Ensure the Content Identifier (CID) is stored in the Distributed Hash Table (DHT) to improve availability.

2. Store CID and Underlying Data in LevelDB for Persistence:
- Persist both the CID and its underlying data in LevelDB to maintain data durability and reliability.

3. Metrics to Track:
- Who/What/Where/BytesScraped/Time Took: Track detailed metrics for each worker.
- Incentivize Time and BytesScraped Totals: Provide incentives based on the total time taken and bytes scraped.
- Number of Scrapes Per Peer: Keep a record of the number of scrapes performed by each peer.

4. Storage of BytesScraped by Peer:
- Store the total bytes scraped by each peer in LevelDB using the peerId as the key.

5. PeerID Selection and Response:
- Implement random selection of peerId.
- Ensure responses are provided by the closest neighbor.

Tasks

1. DHT Integration:
- Implement functionality to store CID in DHT.
- Verify the availability of CID in the DHT.
	
2. LevelDB Integration:
- Implement functionality to store CID and underlying data in LevelDB.
- Verify persistence and retrieval of data from LevelDB.

3. Metrics Tracking:
- Develop a system to track who, what, where, bytes scraped, and the time taken for each operation.
- Implement incentive calculations based on time and bytes scraped.
- Record the number of scrapes per peer.

4. BytesScraped Storage:
- Implement storage of bytes scraped by each peer in LevelDB with peerId as the key.

5. PeerID Selection:
- Implement random selection of peerId.
- Ensure closest neighbor response mechanism is in place.

Additional Information

- Dependencies: Ensure that all changes are compatible with the existing DHT and LevelDB implementations.
- Documentation: Update relevant documentation to reflect the new metrics and storage mechanisms.
- Testing: Thoroughly test all new functionalities to ensure accuracy and reliability.

Labels

- enhancement
- metrics
- storage
- DHT
- LevelDB

**Comment by jdutchak** [comment]
@restevens402 - awaiting PR review
