### ISSUE TITLE
testnet v0.0.5 of Oracle isn't working

### ISSUE THREAD

**Issue by Luka-Loncar** [masa-finance/masa-oracle#318]
https://www.loom.com/share/57f8de0c8caf4dc3bc4cad036db3635d?sid=5f5ee721-7266-4b78-8cd4-ed0ed8eb6b29

One thing I forgot to mention, the one that works is on v.0.0.3

[masa_node.log](https://github.com/user-attachments/files/15592242/masa_node.log)

**Comment by jdutchak** [comment]
Requires port 4001 TCP inbound open for fully integrated workers
