### ISSUE TITLE
Re-Run message and faucet

### ISSUE THREAD

**Issue by Luka-Loncar** [masa-finance/masa-oracle#323]
When you run:

`masa-node --stake 1000
`
it tries to run the node after doing the staking, can you make it just exit after it runs with that flag after it stakes. And display a nice message with details and to re-run after

**Comment by jdutchak** [comment]
This will be in next version 0.0.7-beta along with our own faucet flag

```sh
masa-node --faucet 
or
masa-node --faucet --stake 1000 
```

**Comment by jdutchak** [comment]
"should only allow 1 addr to get 1000 tokens in any 24 hour period"

**Comment by jdutchak** [comment]
Need this to be put into a proper @masa-finance/masa-faucet npm package -- currently have test code deployed via remix. 
@teslashibe who create the npm and deploy? 

I have created a masa faucet smart contract and adding integration to the masa-node for the sepolia network here https://sepolia.etherscan.io/address/0x244813DaABFd59483fe34d1FdB3598AF06fE6c63#code

Awaiting a review by -- @Nolan

"should only allow 1 addr to get 1000 tokens in any 24 hour period"

GOAL: cli changes -- app will exit after any below has completed

```shell
make build
```

```shell
make faucet
```

```shell
make stake
```

then the user can run as normal

```shell
make run
```

deploy params
0xFd36990172dFB44ef0cEa51a9B1159687CfBb4E2
1000000000000000000000

**Comment by Luka-Loncar** [comment]
@miquelcabot can you take @nolanjacobson @jdutchak through how to release the new package?

**Comment by jdutchak** [comment]
![Image](https://github.com/masa-finance/masa-oracle/assets/233619/2dbbe4d9-50bd-4134-997e-60a51fd21f99)
