### ISSUE TITLE
MVP-ready website scraping 

### ISSUE THREAD

**Issue by mudler** [masa-finance/masa-oracle#336]
Currently, the oracle can scrape websites and collect a sentiment analysis result automatically (from LLMs) #166 #163 #167 #187.

We want to make sure this feature is mvp-ready before launching testnet, and asses the quality of it before release.

It seems the `/data/web` endpoint is buggy - see the notes below.

## Acceptance item

- [ ] Make sure that when `depth` is set to `0`, it defaults actually to `1`.
- [ ] QA
- [ ] Identify bugs and open follow-ups if needed, or if chores, fix the bugs found along the way

## Notes

- By default,  `depth` is set to 0, and the scraping request never returns (`depth=0` seems to be invalid)

**Comment by mudler** [comment]
@nolanjacobson are you currently working on this?

**Comment by nolanjacobson** [comment]
@mudler  - yes

**Comment by H34D** [comment]
@nolanjacobson i assigned you to this task now

**Comment by mudler** [comment]
@nolanjacobson can you please reference the issues when opening up PRs? thank you!

PR: https://github.com/masa-finance/masa-oracle/pull/355

@nolanjacobson is left now QA and documentation, right?

**Comment by nolanjacobson** [comment]
@mudler - correct.

**Comment by H34D** [comment]
needs documentation card @nolanjacobson

**Comment by nolanjacobson** [comment]
@Luka-Loncar  - can you create a ticket to do docs for worker scraper?

**Comment by mudler** [comment]
Follow-up card created in https://github.com/masa-finance/masa-oracle/issues/397. Closing this one
