### ISSUE TITLE
Discord Sentiment Analysis

### ISSUE THREAD

**Issue by nolanjacobson** [masa-finance/masa-oracle#346]
## Feature Request

**Summary:**
Implement sentiment analysis for Discord messages using the existing sentiment analysis framework from `sentiment.go`.

**Motivation:**
Sentiment analysis of Discord messages can provide valuable insights into community mood, member engagement, and overall sentiment trends. This can be particularly useful for community managers, moderators, and marketing teams to gauge the impact of announcements, events, or general community sentiment.

**Detailed Explanation:**
The feature should extend the current sentiment analysis capabilities to include Discord messages. It should leverage the existing `AnalyzeSentimentTweets` function's architecture to process Discord messages through the Claude API or other sentiment analysis models.

**Proposed Solution:**
- Develop a new function, `AnalyzeSentimentDiscord`, which mirrors the structure of `AnalyzeSentimentTweets`.
- Extract messages from Discord channels using the Discord API and format them to be compatible with the sentiment analysis models.
- Ensure the function can handle both bulk analysis of historical messages and real-time analysis of new messages.
- Integrate the sentiment analysis results with the existing data pipeline, ensuring results are stored and accessible for reporting and visualization.

**Considerations:**
- The Discord bot must have the necessary permissions to read messages from the target channels.
- The feature must respect Discord's API rate limits and terms of service.
- Ensure robust error handling for API changes, network issues, or interruptions.
- Consider user privacy and data protection laws, especially for private channels or servers.

**Acceptance Criteria:**
- The feature can accurately determine the sentiment of messages from specified Discord channels.
- The sentiment analysis process respects all rate limits and usage policies set by Discord.
- The feature includes unit tests and documentation for maintainability and future development.
- The implementation is compatible with the existing sentiment analysis infrastructure and data storage solutions.

**Comment by mudler** [comment]
@nolanjacobson what's the PR that covered this issue? can you link it please? thank you!

**Comment by nolanjacobson** [comment]
@jdutchak has merged this into his branch. I can't seem to find the PR unfortunately.
