### ISSUE TITLE
spike: handling protocol mismatch between nodes

### ISSUE THREAD

**Issue by Luka-Loncar** [masa-finance/masa-oracle#347]
### Problem
During testing of the latest release, a critical bug was discovered that caused the worker node to crash due to a panic. The panic occurs when there is an interface conversion error, specifically when an interface of type []workers.CID is being incorrectly converted to []interface{}.

```
panic: interface conversion: interface {} is []workers.CID, not []interface {}

goroutine 156 [running]:
github.com/masa-finance/masa-oracle/pkg/workers.updateRecords(0x140013c65b0, {{0x1400596e440, 0x3b}, {0x1400596e340, 0x35}, {0x14003a7eb00, 0x2aa, 0x2c0}, 0x3fce4db48909289e, {0xc192e90543693ec8, ...}})
        /Users/brendanplayford/masa-oracle/pkg/workers/workers.go:227 +0x574
github.com/masa-finance/masa-oracle/pkg/workers.MonitorWorkers({0x10220acc0, 0x14000146dc0}, 0x140013c65b0)
        /Users/brendanplayford/masa-oracle/pkg/workers/workers.go:449 +0x854
created by main.main in goroutine 1
        /Users/brendanplayford/masa-oracle/cmd/masa-node/main.go:97 +0x778
```

Further investigation revealed that this issue arises when older nodes (version 5 or lower) are still running, as there have been breaking changes in the worker code. To resolve this issue and prevent the bug from occurring, we need to explore mechanisms to force the upgrading of all nodes to version 6 or higher.

Currently, attempts to reach out to node operators through Discord and other platforms have been made, but a more robust solution is required at the protocol level to ensure that all nodes are running the compatible version.

## Timebox:
**This spike ticket should be time-boxed to 1 day**

**Comment by teslashibe** [comment]
@jdutchak @Luka-Loncar I simplified the description to be a little more open ended for engineers (aka @jdutchak )

**Comment by mudler** [comment]
@restevens402 are you working on this card?

**Comment by H34D** [comment]
@restevens402 needs PR

**Comment by teslashibe** [comment]
@restevens402 still seeing this crop up on `test` today

```
ERRO[2441] Failed to open stream to 16Uiu2HAmMTA3pJRQLzic39A3KEZNBNymsPYZE2xCVBBKbvC9ph3f: failed to dial: failed to dial 16Uiu2HAmMTA3pJRQLzic39A3KEZNBNymsPYZE2xCVBBKbvC9ph3f: all dials failed
  * [/ip4/127.0.0.1/udp/4001/quic-v1] dial to self attempted
  * [/ip4/86.138.153.168/udp/4001/quic-v1] dial backoff
  * [/ip4/86.138.153.168/udp/14612/quic-v1] dial backoff
  * [/ip4/86.138.153.168/udp/37191/quic-v1] dial backoff
  * [/ip4/86.138.153.168/udp/42432/quic-v1] dial backoff
  * [/ip4/192.168.1.164/udp/4001/quic-v1] context deadline exceeded
  * [/ip4/86.138.153.168/udp/51827/quic-v1] timeout: no recent network activity 
panic: interface conversion: interface {} is []workers.CID, not []interface {}

goroutine 863 [running]:
github.com/masa-finance/masa-oracle/pkg/workers.updateRecords(0x140012927e0, {{0x14005d7f580, 0x3b}, {0x14005d7f4c0, 0x35}, {0x1400190f500, 0x2e2, 0x300}, 0x3fd191878d8eaf97, 0x6682fe84})
        /Users/brendanplayford/masa-oracle/pkg/workers/workers.go:229 +0x564
github.com/masa-finance/masa-oracle/pkg/workers.MonitorWorkers({0x103dc2d50, 0x140005549b0}, 0x140012927e0)
        /Users/brendanplayford/masa-oracle/pkg/workers/workers.go:451 +0x81c
created by main.main in goroutine 1
        /Users/brendanplayford/masa-oracle/cmd/masa-node/main.go:100 +0x778
make: *** [run] Error 2
```

**Comment by restevens402** [comment]
@teslashibe I have added code in the PR to fail on startup if you are on an old version. It's a simple update. It should prevent old nodes from participating on the active network. They could still be connected to old nodes that are also running old versions, but once they restart, they will have to upgrade to join back in.

**Comment by Luka-Loncar** [comment]
@jdutchak small reminder about review here
