### ISSUE TITLE
Implement exact match search for Twitter search query

### ISSUE THREAD

**Issue by teslashibe** [masa-finance/masa-oracle#351]
When we pass an exact match to the Twitter Search API endpoint it does not take the additional "search" quotation marks around the search term. 

### For example: 

![Image](https://github.com/masa-finance/masa-oracle/assets/34052452/c2aefd9f-6462-469f-955e-56f9f6618397)

**Comment by mudler** [comment]
let's close this one and add in the swagger docs the example about exact matches. Follow-up in https://github.com/masa-finance/masa-oracle/issues/459
