### ISSUE TITLE
Add fields to data model to calculate Worker and Validator utility

### ISSUE THREAD

**Issue by theMultitude** [masa-finance/masa-oracle#360]
Follow on to [Define protocol economic model MVP](https://github.com/masa-finance/roadmap/issues/18).

We need to expand the data model to be able to support basic utility functions for Workers and Validators.

Summarizing my findings that I wrote [here](https://github.com/masa-finance/roadmap/issues/18#issuecomment-2181559509):

### Acceptance criteria:

- [ ] `powerScore` -> A scoring of a nodes compute.
- [ ] `threadStatus` -> Whether or not a work thread (request for data was completed) w/ status.
- [ ] `validationStatus` -> Whether or not a work thread has be validated and by whom.

The `powerScore` isn't strictly necessary but if it isn't prohibitively difficult it will aid in further work such as worker selection and confirming Validator requirements.

**Comment by H34D** [comment]
all content from here is in the other tickets

**Comment by theMultitude** [comment]
[This ticket](https://github.com/masa-finance/masa-oracle/issues/382#issue-2380771495) should cover the intention of the contents here.
