### ISSUE TITLE
spike: Restructure Node Data Structures (by node type)

### ISSUE THREAD

**Issue by theMultitude** [masa-finance/masa-oracle#363]
### Problem statement

We need to dig deeper to understand if we can split Node data structures according to node roles so as to limit data stored on each node as well as data passed between nodes.

### Acceptance criteria

- [ ] Separate out data relevant to each Node type
- [ ] Outline how data is moved between nodes to properly tie them together

**Comment by theMultitude** [comment]
@jdutchak and I will discuss and update afterwards.

**Comment by mudler** [comment]
Related work: #383
