### ISSUE TITLE
ci: Container images release

### ISSUE THREAD

**Issue by mudler** [masa-finance/masa-oracle#396]
As part of the release process there should be some consumable artifacts.

This card is about having a github action that deploys a corresponding container image matching releases tag to the public registry, and also having branch-images ready for consumption.

## Acceptance criteria
- [ ] we have a GHA workflow that publishes container images when the oracle repository is tagged
- [ ] The Container images are built along with the codebase in the oracle repository
- [ ] The GHA workflow runs in the `masa-oracle` repository
- [ ] The Dockerfile of the container images doesn't `git clone` the repository, but `COPY` the source
- [ ] The GHA workflow also pushes images for the `main` and `test` branch
- [ ] the images are public and can be pulled by everyone
- [ ] the images don't have sensitive configurations, but can be used with specific network configurations (E.g. testnet, devnet, etc)

**Comment by teslashibe** [comment]
Taking out of v0.6.0 for now and we reprioritize
