### ISSUE TITLE
bug: overestimation of `AccumulatedUptime` in `nodData`

### ISSUE THREAD

**Issue by teslashibe** [masa-finance/masa-oracle#413]
We continue to see the overestimation of `AccumulatedUptime` out of the bounds of the time the network has been live

## An example:

**We have a bug in accumlated uptime calculation**

```
        {
            "multiaddrs": [
                "/ip4/172.89.165.130/udp/41577/quic-v1"
            ],
            "peerId": "16Uiu2HAmMNfDWyMNNF12gKv6bdMDVa1rMat3S3riqtUpNHHbdJp9",
            "firstJoined": 1719957474,
            "lastJoined": 1719967185,
            "lastUpdated": 1719967707,
            "uptime": 772325015789000,
            "uptimeStr": "8 days 22 hours 32 minutes",
            "accumulatedUptime": 869769086152879379,
            "accumulatedUptimeStr": "10066 days 18 hours 31 minutes",
            "ethAddress": "0xfcf04285bf18a18Db4f346E28bfe3914B9776eF7",
            "isActive": true,
            "isStaked": false,
            "isValidator": false,
            "isTwitterScraper": false,
            "isDiscordScraper": false,
            "isWebScraper": false,
            "bytesScraped": 0,
            "version": "0.0.9-beta"
        },
```

**Comment by teslashibe** [comment]
@Luka-Loncar @mudler I moved this back to in review. This QA ticket https://github.com/masa-finance/roadmap/issues/67 needs to be completed so we can mark this as done for this release. We cannot fully test this until v0.6 get released on test next week and all nodes update.

**Comment by mudler** [comment]
> @Luka-Loncar @mudler I moved this back to in review. This QA ticket [masa-finance/roadmap#67](https://github.com/masa-finance/roadmap/issues/67) needs to be completed so we can mark this as done for this release. We cannot fully test this until v0.6 get released on test next week and all nodes update.
> 
> @restevens402 and I are working on this

isn't this covered by https://github.com/masa-finance/masa-oracle/issues/426 already (which is marked after 0.6)? I'm fine either way, but one of the two should be closed

**Comment by mudler** [comment]
I'm going to close this in favor of https://github.com/masa-finance/masa-oracle/issues/426 as work on this one was already done (PR was merged, and potential fix is already available in the code)
