### ISSUE TITLE
Add Initial Analytics Event Triggers

### ISSUE THREAD

**Issue by theMultitude** [masa-finance/masa-oracle#419]
Follow up implementation from #383 

This is meant to be a quick implementation to begin firing granular events from the protocol to our [REST Gateway](https://github.com/masa-finance/masa-oracle-infra/issues/68) to be deposited in [S3](https://github.com/masa-finance/masa-oracle/issues/250). 

This will be followed up by a more complete [SDK implementation](https://github.com/masa-finance/masa-oracle/issues/297) and development.

Acceptance Criteria:
- [ ] Identify optimal tracking locations for events in [this](https://github.com/masa-finance/masa-oracle/issues/383#issuecomment-2214586904) comment.
- [ ] Document event structure.
- [ ] Embed event firing functionality.
- [ ] Verify events are firing and being stored properly.

**Comment by theMultitude** [comment]
@teslashibe ticket related to adding initial event triggers. Crossposting suggested format.

```
{
  "headers": {
    "eventId": "abc1234-def5678-ghi9012",
    "eventType": "WorkAssignment",
    "timestamp": "2024-08-07T15:10:00Z",
    "version": "1.0" --> Versioning allows us to track iterations to event structure
  },
  "body": {
    "taskId": "task7890", --> if possible.
    "assignedBy": "oracleNode123",
    "assignedTo": "workerNode456",
    "taskDetails": {
      "taskType": "dataProcessing",
      "dataCID": "Qm1234abcd5678efgh9012",
      "totalBytes: "2400"
      "parameters": { --> if necessary or helpful
        "param1": "value1",
        "param2": "value2"
      }
    }
}
```

**Comment by teslashibe** [comment]
@theMultitude I have started and very simple event tracking package here: https://github.com/masa-finance/masa-oracle/pull/513

It is extremely simple and this is meant to be low hanging fruit. 

@mudler this is completed and will go into v0.7.0 one we have completed this ticket: https://github.com/masa-finance/masa-oracle/issues/512

I am breaking up tickets more and making smaller PRs focused on packages that are functional and incremental in implementation.

**Comment by mudler** [comment]
> @theMultitude I have started and very simple event tracking package here: #513
> 
> It is extremely simple and this is meant to be low hanging fruit.
> 
> @mudler this is completed and will go into v0.7.0 one we have completed this ticket: #512
> 
> I am breaking up tickets more and making smaller PRs focused on packages that are functional and incremental in implementation.

gotcha - shall we close this one in favor of https://github.com/masa-finance/masa-oracle/issues/512 and #512 then?

**Comment by mudler** [comment]
closing in favor of #512, handled in #525
