### ISSUE TITLE
Ensure all documentation is updated to reflect new features in v0.5 and v0.6

### ISSUE THREAD

**Issue by Luka-Loncar** [masa-finance/masa-oracle#424]
Following the release of v0.5, we need to ensure that all documentation is updated to accurately reflect the new features and functionalities. This task is crucial for maintaining clear communication with our users and developers.

**Objective:**
Update all relevant documentation to include information about the following new features:

- [x] Discord scraping
- [x] Telegram scraping
- [x] Website scraping
- [x] Decentralized distributed work model
- [x] LLM /chat endpoint

Acceptance Criteria:

- [ ] All new features are clearly explained in the documentation
- [ ] Documentation is consistent with the current implementation
- [ ] New features are integrated seamlessly into existing documentation structure
- [ ] Updated documentation has been reviewed by at least one other team member
- [ ] All links and references within the documentation are functional and up-to-date
- [ ] scan quickly the changeset from v0.5 to v0.6 that needs documentation and add the sections that are not covered by docs

**Comment by mudler** [comment]
I see the discord API is already documented here: 

- https://developers.masa.ai/docs/masa-oracle/oracle-node/discord-data

Web scraping is documented here:

https://developers.masa.ai/docs/masa-oracle/oracle-node/web-scraper-data

>  Decentralized distributed work model 

What needs to be documented here? this is nothing that is exposed to the user so I'm not sure what value adds to have it in the documentation

>  LLM /chat endpoint

This is missing indeed

**Comment by mudler** [comment]
Also part of this one to scan quickly the changeset from v0.5 to v0.6 that needs documentation
