### ISSUE TITLE
fix: private ip address issue in node data

### ISSUE THREAD

**Issue by jdutchak** [masa-finance/masa-oracle#439]
# Problem

Currently the private ip address of a node can find its way into the node data on a worker node. The node data is used to filter through validators and workers and this requires the public ip to always be stored in the node data for processing.

functions handling this 
GetPriorityAddress
getBestPublicAddress
isPreferredAddress

**Comment by mudler** [comment]
@jdutchak is going to share to @teslashibe the services used to identify the public IPs so we can pay one of the services to be reliable until https://github.com/masa-finance/roadmap/issues/69 is worked out
