### ISSUE TITLE
bug: fix Telegram broken context for client persisting

### ISSUE THREAD

**Issue by nolanjacobson** [masa-finance/masa-oracle#453]

**Comment by nolanjacobson** [comment]
@mudler

**Comment by mudler** [comment]
We are moving on with this one, and have a follow-up for refactoring and optimizations in https://github.com/masa-finance/masa-oracle/issues/460. The PR https://github.com/masa-finance/masa-oracle/pull/456 currently has a workaround which involves re-creating the context on each request to the Telegram API.

@nolanjacobson will update the follow-up ticket with more context
