### ISSUE TITLE
v0.5.0-test : oracle_protocol is error version

### ISSUE THREAD

**Issue by IONodeOnline** [masa-finance/masa-oracle#455]
Make run is error version

WARN[0000] No staking event found for this address
WARN[0005] [-] Failed to get public IP: Results are not identical: [152.53.45.234 152.53.45.234 2a0a:4cc0:0:20ef:473:1aff:feb2:c859 2a0a:4cc0:0:20ef:473:1aff:feb2:c859 152.53.45.234 152.53.45.234 2a0a:4cc0:0:20ef:473:1aff:feb2:c859 2a0a:4cc0:0:20ef:473:1aff:feb2:c859 152.53.45.234 2a0a:4cc0:0:20ef:473:1aff:feb2:c859 2a0a:4cc0:0:20ef:473:1aff:feb2:c859]
http://ip.appspot.com status code 503, body:
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>503 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The service you requested is not available yet.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>

Failed to reach https://shtuff.it/myip/short
Failed to reach http://bot.whatismyipaddress.com
WARN[0005] [-] No suitable address found, returning the first entry
INFO[0005] [+] Starting node with ID: /ip4/152.53.45.234/udp/4001/quic-v1/p2p/16Uiu2HAmAdRMyaWLA5UBoNQH7Mw7bKFHbNoVYVnYkqksqbfWsTHZ
INFO[0005] [+] Peer added to DHT: 16Uiu2HAmPxXXjR1XJEwckh6q1UStheMmGaGe8fyXdeRs3SejadSa
INFO[0005] [+] Successfully added bootstrap peer 16Uiu2HAmPxXXjR1XJEwckh6q1UStheMmGaGe8fyXdeRs3SejadSa to DHT
INFO[0005] [+] Peer added to DHT: 16Uiu2HAmKULCxKgiQn1EcfKnq1Qam6psYLDTM99XsZFhr57wLadF
ERRO[0005] [-] Connection failed for peer: 16Uiu2HAmKULCxKgiQn1EcfKnq1Qam6psYLDTM99XsZFhr57wLadF failed to dial: failed to dial 16Uiu2HAmKULCxKgiQn1EcfKnq1Qam6psYLDTM99XsZFhr57wLadF: no addresses
INFO[0005] [+] Successfully added bootstrap peer 16Uiu2HAmKULCxKgiQn1EcfKnq1Qam6psYLDTM99XsZFhr57wLadF to DHT
INFO[0005] [+] Connection established with node: {16Uiu2HAmPxXXjR1XJEwckh6q1UStheMmGaGe8fyXdeRs3SejadSa: [/ip4/35.223.224.220/udp/4001/quic-v1]}
INFO[0005] [+] Peer added to DHT: 16Uiu2HAmMxU66HfQ2mpQYXK21wuWHzbeGBdYNMyr74FKsPqqngG6
INFO[0005] [+] Peer added to DHT: 16Uiu2HAmQXiKZKrGFK5hBdB9u57ymtmieaVzW8Kqw62s3SqN92Vp
INFO[0005] [+] Peer added to DHT: 16Uiu2HAmK2T2qgxZNzRYTjDFTpdqkWCyJxrw7vXkVFy4ctETrFRW
INFO[0005] [+] Peer added to DHT: 16Uiu2HAkyvBsCJST421V6w7MXXtYYFcDy41xVYuBtiv1Foweqh5q
INFO[0005] [+] Peer added to DHT: 16Uiu2HAkyRuvHrtu8iaotCtT8eidMypdyb9PqtYQTnShYhDeHY3B
INFO[0005] [+] Peer added to DHT: 16Uiu2HAm89Sj8xQXXvKVVmG13ELam2PhECDrhPjs1f9aXuF1fqeh
INFO[0005] [+] Peer added to DHT: 16Uiu2HAmB8gEmGAueDugPaHvPdeKQ3grxnj2YRVKp3SpYVAo3yh4
INFO[0005] [+] Peer added to DHT: 16Uiu2HAkzF8cmqJDg3eeTYACydCL8UQLf9f86UNuYfVtv23PayXV
INFO[0005] [+] Peer added to DHT: 16Uiu2HAm1cmCTocSvZQUjrdbTAW3sUxSMTNsPHWiAokcvwfHQCD3
INFO[0005] [+] Peer added to DHT: 16Uiu2HAmGyu1Vu4QX9axCEacWJotzXzXGzoJ6bSAhpa2aJuNRcUP
INFO[0005] [+] Peer added to DHT: 16Uiu2HAmFPEyymdTiC43MrnAaWt2kBUCcEgCmdgJ9fyWz9StDK3Z
INFO[0005] [+] Connection established with node: {16Uiu2HAmKULCxKgiQn1EcfKnq1Qam6psYLDTM99XsZFhr57wLadF: [/ip4/34.121.111.128/udp/4001/quic-v1]}
INFO[0005] [+] Peer added to DHT: 16Uiu2HAm8M9gZfMYmj44R9ibfY1bGzctgk35fM2sSfE8DAY4m8X9
INFO[0005] [+] Peer added to DHT: 16Uiu2HAmDEqy7ypNxLfx8WNThxQ2yGKpby1CHGjEKz58SyT1bBqQ
INFO[0006] [+] Peer added to DHT: 16Uiu2HAm2TTo54UxRUypHm1EzGcCPf2vdgqexZfEwdj5U2CLZV8S
INFO[0006] [+] Peer added to DHT: 16Uiu2HAmLSth1ezp9Kftb6EsNvt8PvS1ZeNDpq7FHHLdUibQ1w5b
INFO[0006] [+] Peer added to DHT: 16Uiu2HAmD9PXtsx8ffdCkQw6WV2uT7ThiofTb5dCmmGBuNY8fvTq
FATA[0006] [-] failed to negotiate protocol: protocols not supported: [/masa/oracle_protocol/v0.5.0-test] Please update to the latest version and make sure you are connecting to the correct network.
make: *** [Makefile:11: run] Error 1

**Comment by teslashibe** [comment]
@IONodeOnline thanks for the issue - we are working on a fix
