### ISSUE TITLE
Create a public instance with 3/4 workers with Twitter scraping capabilities

### ISSUE THREAD

**Issue by mudler** [masa-finance/masa-oracle#508]
## Problem

We want to have a small isolated network that we can use for demos and show-off

## Acceptance criteria

- [ ] There is an isolated network of bootnodes attached to the main branch
- [ ] We have a set of workers that have configured twitter for scraping
- [ ] the Playground UI uses this new network

**Comment by mudler** [comment]
I'm wondering here.. why we can't use libp2p bootnodes for testing?

**Comment by teslashibe** [comment]
@teslashibe to connect DO machines to the `api-1` cluster

**Comment by Luka-Loncar** [comment]
Is this going to be released in v0.8 or should I move it to v0.8.1?

**Comment by Luka-Loncar** [comment]
Acceptance criteria is met, but we need follow up ticket since the implementation isn't working fully as expected. @mudler @teslashibe 

We have been discussing leveraging subnet for this.
