### ISSUE TITLE
feat: increase AWS cluster size and specs

### ISSUE THREAD

**Issue by teslashibe** [masa-finance/masa-oracle#539]
## Problem 

We have no redundancy in our AWS node cluster so if the main `api-1` node fails the entire cluster goes down:

### Adding some redundancy in the AWS would be good. 

**We could have the following** 

1. `api-2` - configured the same base as `api-1` and connected to `api-1` as a bootnode
2. `api-3` - configured the same base as `api-1` and connected to `api-1` and `api-2` as a bootnodes

They should all be **beefy** instances that are not shared resources that will give nice redundancy on network for `dht` propagation. API calls could then be load balanced over all three nodes.

**Comment by teslashibe** [comment]
Hi @j2d3 this is great do you think you can make one more change. I am still seeing the same resource limit exceed issue on our instance. 

This is a comparison of what we used in GCP, what we are using in AWS, and what I propose we move to for the three nodes in the cluster. 

## Instance Comparison:
1. n2-standard-8 (GCP, previous): 8 vCPUs, 32 GB RAM
2. t3.large (AWS, current): 2 vCPUs, 8 GB RAM, burstable
3. m5.2xlarge (**AWS, proposed**): 8 vCPUs, 32 GB RAM

## Why m5.2xlarge:
1. **Resource Upgrade**: 4x CPU and RAM vs. t3.large
2. **Consistent Performance**: Non-burstable, unlike t3
3. **libp2p Optimized**: 
   - More resources for multiple p2p connections
   - Sufficient RAM for connection states and buffers
4. **API Ready**: Handles variable load without CPU credit concerns
5. **Network**: Up to 10 Gbps vs. 5 Gbps on t3.large
6. **Scalability**: Easy vertical scaling within m5 family

## Why t3.large is problematic:
- Insufficient CPU/RAM for libp2p workload
- Burstable performance causes inconsistency
- Likely exhausting CPU credits, leading to performance drops

Let me know what you think.

**Comment by teslashibe** [comment]
@Luka-Loncar @5u6r054 I re-opened this due to the issue same resource allocation issue being problematic today.

**Comment by teslashibe** [comment]
@5u6r054 what EBS drive do we have connected to the instance? 

Something like `gp3 SSD` should have enough IO to work with this setup. But I don't know what we are currently using.

**Comment by 5u6r054** [comment]
Another thing, if you are trying to make twitter requests on api-1, apix-1, and apix-2, since api-1 is acting as bootnode, and the other 2 are just - supporting it and taking round robin swagger requests, twitter endpoint requests will fail because there are no twitter workers in this network.

To avoid this, these instances should use the testnet bootnode, and join to the "real" network. They are running the same version (latest tagged release), and if they are part of the "real" network, they will be able to do all work requests for which there are workers.

**Comment by mudler** [comment]
where are with this one @5u6r054 ?
