### ISSUE TITLE
feat(workers): Implement adaptive worker selection for improved task distribution

### ISSUE THREAD

**Issue by teslashibe** [masa-finance/masa-oracle#544]
## Problem:
The current worker selection process is inefficient, often failing to utilize all available workers and potentially leading to increased latency and uneven work distribution.

## Acceptance Criteria:
1. Implement a scoring system for worker reliability and performance.
2. Create a cache of recently successful workers.
3. Develop a selection algorithm that chooses a subset of high-scoring, available workers.
4. Implement fallback mechanism to try additional workers if initial attempts fail.
5. Ensure the system adapts by updating worker scores based on performance.
6. Maintain or improve current task completion success rate.
7. Reduce average latency for task completion by at least 20%.
8. Handle at least 30% more concurrent tasks without degradation in performance.
9. Add logging for worker selection process to aid in debugging and optimization.
10. Include unit tests for new components and integration tests for the overall worker selection process.

## Out of Scope:
- Changes to the underlying network protocol
- Modifications to the actual task execution logic

**Comment by teslashibe** [comment]
@Luka-Loncar add this to `0.8.1` please

**Comment by teslashibe** [comment]
Do we kill this in favor of https://github.com/masa-finance/masa-oracle/issues/507 or do we merge the two to become a hybird?

**Comment by mudler** [comment]
This card have a lot of overlap with #507 indeed, in the planning we decided to mark #507 as a blocker for this one because the gossip mechanism could actually fix this issue as well with it.

This issue would require also a general brainstorming session (#568) to discuss how to improve worker selection (even by the quality of the responses), which could influence where are we going with this one.

**Comment by teslashibe** [comment]
@restevens402 I am observing on the testnet nodes that are configured to accept tweets take on the work and be available to connect. But because they are not configured (I am assuming). They do not return work and timeout. 

The problem here is that we continue to round-robin faulty nodes.

Therefore, I think selecting a node that has been successful in returning a response as a priority would be a good first step. We may also want to have a periodic heartbeat that pings nodes a query to make sure the list stays updated with the ones that respond at the top. 

I think this means that we need to add a field to nodeData to to track the following:

returnedTweets: int
lastReturnedTweet: timestamp 
tweetTimeout: boolean

We can then sort workers by returnedTweets and timestamp and use this as our selection criteria, we would **exclude** nodes that have timed out. 

```
INFO[0300] [+] Routing table size: 36
INFO[0305] Mapping WorkerType twitter to WorkerCategory
INFO[0305] WorkerType is related to Twitter
INFO[0305] Event tracked                                 data="{worker_failure 16Uiu2HAmFDYCmhBQ5VcyhcmEu9QF6vmY2QJ3wZFrxCWWvGNH2JKx  twitter twitter false false 0 work execution timed out}" event_name=worker_failure
INFO[0305] Event sent                                    event_name=worker_failure
ERRO[0305] error sending work to worker: 16Uiu2HAmFDYCmhBQ5VcyhcmEu9QF6vmY2QJ3wZFrxCWWvGNH2JKx: work execution timed out
INFO[0305] Remote worker 16Uiu2HAmFDYCmhBQ5VcyhcmEu9QF6vmY2QJ3wZFrxCWWvGNH2JKx failed, moving to next worker
INFO[0305] Attempting remote worker 16Uiu2HAm8BpRkVN6zNKyTo7R2VfwZkAmxvDvxoD5wJ3CMnyL7BMS (attempt 3/10)
INFO[0305] Mapping WorkerType twitter to WorkerCategory
INFO[0305] WorkerType is related to Twitter
INFO[0305] Event tracked                                 data="{work_distribution 16Uiu2HAm8BpRkVN6zNKyTo7R2VfwZkAmxvDvxoD5wJ3CMnyL7BMS  twitter twitter true false 0 }" event_name=work_distribution
INFO[0305] Event sent                                    event_name=work_distribution
INFO[0311] [+] Successfully advertised protocol: /masa/oracle_protocol/v0.8.0-test
INFO[0351] Mapping WorkerType twitter to WorkerCategory
INFO[0351] WorkerType is related to Twitter
INFO[0351] Event tracked                                 data="{worker_failure 16Uiu2HAm8BpRkVN6zNKyTo7R2VfwZkAmxvDvxoD5wJ3CMnyL7BMS  twitter twitter false false 0 work execution timed out}" event_name=worker_failure
INFO[0351] Event sent                                    event_name=worker_failure
ERRO[0351] error sending work to worker: 16Uiu2HAm8BpRkVN6zNKyTo7R2VfwZkAmxvDvxoD5wJ3CMnyL7BMS: work execution timed out
INFO[0351] Remote worker 16Uiu2HAm8BpRkVN6zNKyTo7R2VfwZkAmxvDvxoD5wJ3CMnyL7BMS failed, moving to next worker
WARN[0356] Failed to find peer 16Uiu2HAmKA2LQTtyfc44cfgzf5toxA1gJDoTgjX4ezKBJD2XM35T in DHT: routing: not found
INFO[0360] Removing stale peer: 16Uiu2HAmU1RgnKYKNU7vE6HdBGZ97Ba7jvTCf45hiZDLvwx7DMds
INFO[0360] [+] Routing table size: 36
WARN[0361] Failed to find peer 16Uiu2HAkwLrLah7UQbFsdJ4ytvYX3kHscg4GxwTWQyfTSUqWKyjc in DHT: routing: not found
INFO[0361] Removing stale peer: 16Uiu2HAmFoUdEbgTzCNad2gEnakbxUKFDie8hfwwcZJyoghtmdVY
WARN[0362] Failed to find peer 16Uiu2HAmSvJoRMKKobFDtQcadbPhoeJPwRWcjUpxpebosQGDT8nE in DHT: routing: not found
WARN[0362] Failed to find peer 16Uiu2HAmT43ct3zkDSrannmkhG919T3YrXD7pUFG2zsfY6uti8qh in DHT: routing: not found
INFO[0362] Attempting remote worker 16Uiu2HAmRjxL2htbBFD4LMNmNSP1XYYS8QjARwzPR8Z2dQggVudp (attempt 8/10)
INFO[0362] Mapping WorkerType twitter to WorkerCategory
INFO[0362] WorkerType is related to Twitter
INFO[0362] Event tracked                                 data="{work_distribution 16Uiu2HAmRjxL2htbBFD4LMNmNSP1XYYS8QjARwzPR8Z2dQggVudp  twitter twitter true false 0 }" event_name=work_distribution
INFO[0362] Event sent                                    event_name=work_distribution
INFO[0363] Removing stale peer: 16Uiu2HAmJ4KdBqaeBFDqV7DuAg7TgsVQzCWkSAZgeGQ1YhSBxU1e
ERRO[0364] response channel is blocking for request ID: ae2ec264-8ad4-4700-b09d-51e6eb735e58
[GIN] 2024/10/07 - 09:42:39 | 504 |         1m50s |             ::1 | POST     "/api/v1/data/twitter/tweets/recent"
```

**Comment by restevens402** [comment]
To add sorting to the code:


	1. Update the NodeData struct in node_data.go to include the new fields.
	2. Implement sorting logic using the "By" pattern in node_event_tracker.go.
	3. Update the GetEligibleWorkerNodes function in worker_selection.go to call the sort function based on the new fields.

### Step 1: Update NodeData Struct

Add the new fields to the NodeData struct in node_data.go:

```
type NodeData struct {
    // ... existing fields ...
    ReturnedTweets     int       `json:"returnedTweets,omitempty"`
    LastReturnedTweet  time.Time `json:"lastReturnedTweet,omitempty"`
    TweetTimeout       bool      `json:"tweetTimeout,omitempty"`
    TweetTimeouts      int       `json:"tweetTimeouts,omitempty"`
    LastTweetTimeout   time.Time `json:"lastTweetTimeout,omitempty"`
    // ... existing fields ...
}
```

### Step 2: Implement Sorting Logic

Create a sorting function using the "By" pattern in node_event_tracker.go:

```
type By func(n1, n2 *NodeData) bool

func (by By) Sort(nodes []NodeData) {
    ns := &nodeSorter{
        nodes: nodes,
        by:    by,
    }
    sort.Sort(ns)
}

type nodeSorter struct {
    nodes []NodeData
    by    func(n1, n2 *NodeData) bool
}

func (s *nodeSorter) Len() int {
    return len(s.nodes)
}

func (s *nodeSorter) Swap(i, j int) {
    s.nodes[i], s.nodes[j] = s.nodes[j], s.nodes[i]
}

func (s *nodeSorter) Less(i, j int) bool {
    return s.by(&s.nodes[i], &s.nodes[j])
}

//TODO: this is where we implement the sorting logic we want to be applied
// I used ReturnedTweets and the LastReturnedTweet as an example start.
func sortByTwitterReliability(nodes []NodeData) {
    By(func(n1, n2 *NodeData) bool {
        if n1.ReturnedTweets != n2.ReturnedTweets {
            return n1.ReturnedTweets > n2.ReturnedTweets
        }
        return n1.LastReturnedTweet.After(n2.LastReturnedTweet)
    }).Sort(nodes)
}
```


### Step 3: Update GetEligibleWorkerNodes Function

Modify the GetEligibleWorkerNodes function in worker_selection.go to sort the nodes:

```
func GetEligibleWorkers(node *node.OracleNode, category pubsub.WorkerCategory) ([]data_types.Worker, *data_types.Worker) {
    workers := make([]data_types.Worker, 0)
    nodes := node.NodeTracker.GetEligibleWorkerNodes(category)

    // Sort nodes by returnedTweets and lastReturnedTweet
    sortByReturnedTweetsAndLastReturnedTweet(nodes)

    var localWorker *data_types.Worker
    
//    TODO: removethe shuffle since we are sorting now
//    rand.Shuffle(len(nodes), func(i, j int) {
//        nodes[i], nodes[j] = nodes[j], nodes[i]
//    })

    logrus.Info("Getting eligible workers")
    for _, eligible := range nodes {
        if eligible.PeerId.String() == node.Host.ID().String() {
            localAddrInfo := peer.AddrInfo{
                ID:    node.Host.ID(),
                Addrs: node.Host.Addrs(),
            }
            localWorker = &data_types.Worker{IsLocal: true, NodeData: eligible, AddrInfo: &localAddrInfo}
            continue
        }
        workers = append(workers, data_types.Worker{IsLocal: false, NodeData: eligible})
    }

    logrus.Infof("Found %d eligible remote workers", len(workers))
    return workers, localWorker
}
```

If we think we will implement multiple ways to sort the node data, it would make sense to have a NodeSorter struct that we can encapsulate it in.

**Comment by mudler** [comment]
Covered by https://github.com/masa-finance/masa-oracle/pull/589
