### ISSUE TITLE
Have a brainstorming session about malicious workers

### ISSUE THREAD

**Issue by mudler** [masa-finance/masa-oracle#568]
## Problem

Miners could edit the oracle code and fake/mock scraping answers (e.g. Twitter tweets) to have an high incentive and award

## Action item

- [x] Set up a call to discuss and brainstorm the problem
- [x] Create follow-up cards as needed
- [x] Consider the tickets in Context ⬇ 

## Context

- #563 
- #562

**Comment by teslashibe** [comment]
@restevens402 @teslashibe @theMultitude @mudler to do this brainstorming session. @teslashibe to book

**Comment by teslashibe** [comment]
An idea here that crosses over, ensure a hotkey has a valid staked worker on the protocol. If fraudulent activity the stake is slashed. This slashing mechanism is in addition to the blacklist penalty and loss of registration fee that must be greater than the daily reward for miners on the subnet.

**Comment by mudler** [comment]
We had the conversation, follow-up in: https://github.com/masa-finance/product-issues/issues/87
