### ISSUE TITLE
spike: Tracking the number of accounts a miner has setup

### ISSUE THREAD

**Issue by giovaroma** [masa-finance/masa-oracle#622]
## Problem

- we do not formally know the capacity of all the miners in the network
- How many logins users do have
  - We can only see that by observing "passively" the events in the network (e.g. errors)
- We currently cannot measure network capacity/efficiency
- We do not know the state of some the nodes this is to be further defined by Chris chatting with Bob.

## Acceptance criteria

- [ ] We know of an approach that we can use to track how many accounts are set by a peer id
- [ ] This information can be used and tracked via API

### Notes:

We had a report on the testnet that a miner is taking advantage of the testnet campaign but this cannot be validated. To further understand this we would need to be able to:

Tracking the number of accounts a miner has setup because out performance might just be that they added more accounts recently therefore they have more capacity 

Slack conversation for full context here: https://masafinance.slack.com/archives/C028C3D5FD3/p1730827864336509

**Comment by theMultitude** [comment]
A [loom](https://www.loom.com/share/65091f08c1ef4188982b3ada7d694a44?sid=1b9a5761-a6f4-4575-b2c5-6ab671ba7a34) and [notebook](https://deepnote.com/workspace/masa-analytics-d68a9273-a2c8-45ce-9e9d-355017b5d9ef/project/Protocol-Dashboard-d0afbaed-d575-43de-9bc0-07ef0d2bfd33/notebook/Number-of-Twitter-Accounts-per-Worker-f6bf05c031e240e0b6740b6abf57fe79) detailing my findings.

**Comment by theMultitude** [comment]
Essentially I backed into this information by picking the unique authentication errors by peer_id to get a count of the unique usernames associated with each.

**Comment by mudler** [comment]
@theMultitude is there anything needed from this card left?

**Comment by restevens402** [comment]
Notes:  

- make sure the uuid is readily available everywhere we send events
- Event service needs a new event LoginEvent with corresponding table
    - PeerId
    - service user id
    - timestamps that are useful
    - success/failure
    - error (optional)
    - service type (Twitter / Discord etc)
- Add to the Nodes event service to call the actual Event Service
- Add sending the event in the workflow for twitter

**Comment by restevens402** [comment]
Here are the changes that are needed for the masa-protocol-api


# LoginEvent - masa-protocol-api

###  1.  Define the LoginEvent Model

Create a new file, login_event.go, in the models package to define the LoginEvent model. This model will map to the login_events table in your database.

create something like login_event.go

```go
package models

import "time"

// LoginEvent represents a user login event in the system.
type LoginEvent struct {
    ID          uint      `json:"id" gorm:"primaryKey"`
    PeerID      string    `json:"peer_id" gorm:"column:peer_id;not null"`
    UserID      string    `json:"user_id" gorm:"column:user_id;not null"`
    CreatedAt   time.Time `json:"created_at" gorm:"column:created_at;autoCreateTime"`
    UpdatedAt   time.Time `json:"updated_at" gorm:"column:updated_at;autoUpdateTime"`
    Success     bool      `json:"success" gorm:"column:success;not null"`
    Error       string    `json:"error" gorm:"column:error"`
    ServiceType string    `json:"service_type" gorm:"column:service_type;not null"`
}

// TableName sets the insert table name for this struct type
func (LoginEvent) TableName() string {
    return "login_events"
}
```


### 2. Update the Database Schema

Ensure the database schema is updated to include the login_events table. You can use GORM's auto-migration feature to create the table:

```go
import (
    "gorm.io/gorm"
    "masa-protocol-api/pkg/models"
)

func Migrate(db *gorm.DB) error {
    return db.AutoMigrate(&models.LoginEvent{})
}
```


### 3. Create the handlers you need

This can be in a separate file like login_event_handler.go that would look something like:

```go
package handlers

import (
	"github.com/gofiber/fiber/v2"
	"github.com/masa-finance/masa-protocol-api/pkg/db"
	"github.com/masa-finance/masa-protocol-api/pkg/models"
	"github.com/sirupsen/logrus"
)

// CreateLoginEvent handles the creation of a new login event.
func CreateLoginEvent(c *fiber.Ctx) error {
	var loginEvent models.LoginEvent
	if err := c.BodyParser(&loginEvent); err != nil {
		logrus.WithError(err).Error("Failed to parse login event payload")
		return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{"error": "Invalid request body"})
	}

	if err := db.DB.Create(&loginEvent).Error; err != nil {
		logrus.WithError(err).Error("Failed to create login event")
		return c.Status(fiber.StatusInternalServerError).JSON(fiber.Map{"error": "Failed to create login event"})
	}

	return c.Status(fiber.StatusCreated).JSON(loginEvent)
}

// GetLoginEvents handles retrieving all login events.
func GetLoginEvents(c *fiber.Ctx) error {
	var events []models.LoginEvent
	if err := db.DB.Find(&events).Error; err != nil {
		logrus.WithError(err).Error("Failed to retrieve login events")
		return c.Status(fiber.StatusInternalServerError).JSON(fiber.Map{"error": "Failed to retrieve login events"})
	}

	return c.JSON(events)
}
```

### 4. Add API Endpoints

Add API endpoints to create and retrieve LoginEvent records. This might be in a file like routes.go.

```go
package api

import (
	"github.com/gofiber/fiber/v2"
	"github.com/masa-finance/masa-protocol-api/pkg/handlers"
	eventHandler "github.com/masa-finance/masa-protocol-api/pkg/handlers/event"
	"github.com/sirupsen/logrus"
)

// SetupRoutes configures all the routes for the application.
func SetupRoutes(app *fiber.App) {
	// Add global middleware for logging
	app.Use(func(c *fiber.Ctx) error {
		logrus.WithFields(logrus.Fields{
			"method": c.Method(),
			"path":   c.Path(),
			"ip":     c.IP(),
			"body":   string(c.Body()),
		}).Info("Incoming request")
		return c.Next()
	})

	nodeGroup := app.Group("/node")
	nodeGroup.Post("/v1/data", handlers.SaveNodeData)
	nodeGroup.Get("/v1/data", handlers.GetNodeData)
	app.Post("/v1/events", eventHandler.ReceiveEvent)

	// Group for login events
	loginGroup := app.Group("/v1/login-events")
	loginGroup.Post("/", eventHandler.CreateLoginEvent)
	loginGroup.Get("/", eventHandler.GetLoginEvents)
}
```

### 5. Update Documentation

Ensure your project documentation is updated to reflect the new LoginEvent functionality, including API endpoints and data model descriptions.

There is a swagger file that should be updated.

**Comment by restevens402** [comment]
# LoginEvent - masa-oracle


To integrate the new LoginEvent functionality, you can create a new file login_event.go in the event package and update the event_client.go to include methods for sending LoginEvent data. Here's how you can do it:

### Step 1: Create login_event.go

Create a new file login_event.go in the masa-oracle/pkg/event directory. This file will define the LoginEvent struct and any related methods

```go
package event

import (
	"time"
)

// LoginEvent represents a user login event.
type LoginEvent struct {
	ID          uint      `json:"id"`
	PeerID      string    `json:"peer_id"`
	UserID      string    `json:"user_id"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	Success     bool      `json:"success"`
	Error       string    `json:"error,omitempty"`
	ServiceType string    `json:"service_type"`
}

// NewLoginEvent creates a new LoginEvent instance.
func NewLoginEvent(peerID, userID, serviceType string, success bool, error string) *LoginEvent {
	return &LoginEvent{
		PeerID:      peerID,
		UserID:      userID,
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
		Success:     success,
		Error:       error,
		ServiceType: serviceType,
	}
}
```


### Step 2: Update event_client.go

Add methods to event_client.go to send LoginEvent data to the server in event_client.go

```go
package event

// ... existing imports ...

// SendLoginEvent sends a LoginEvent to the server.
func (c *EventClient) SendLoginEvent(event *LoginEvent) error {
	if c == nil {
		return fmt.Errorf("EventClient is nil")
	}

	url := fmt.Sprintf("%s/%s/login-events", c.BaseURL, APIVersion)
	payload, err := json.Marshal(event)
	if err != nil {
		c.Logger.WithError(err).Error("Failed to marshal login event")
		return err
	}

	resp, err := c.HTTPClient.Post(url, "application/json", bytes.NewBuffer(payload))
	if err != nil {
		c.Logger.WithError(err).Error("Failed to send login event")
		return err
	}
	defer func(Body io.ReadCloser) {
		err := Body.Close()
		if err != nil {
			c.Logger.WithError(err).Error("Failed to close body")
		}
	}(resp.Body)

	if resp.StatusCode != http.StatusOK {
		err = fmt.Errorf("login event service returned non-OK status: %d", resp.StatusCode)
		c.Logger.WithError(err).Error("Failed to send login event")
		return err
	}

	c.Logger.WithFields(logrus.Fields{
		"peer_id":      event.PeerID,
		"user_id":      event.UserID,
		"service_type": event.ServiceType,
	}).Info("Login event sent")

	return nil
}
```


### Step 3. Add the call to SendLoginEvent to the Twitter Auth code
in pkg/scrapters/twitter/auth.go modify the code to send the LoginEvent. Here is an example of how that could be done:

```go
package twitter

import (
	"fmt"
	"time"

	"github.com/sirupsen/logrus"
	"github.com/masa-oracle/pkg/event" // Import the event package
)

func NewScraper(account *TwitterAccount, cookieDir string) *Scraper {
	scraper := &Scraper{Scraper: newTwitterScraper()}

	if err := LoadCookies(scraper.Scraper, account, cookieDir); err == nil {
		logrus.Debugf("Cookies loaded for user %s.", account.Username)
		if scraper.IsLoggedIn() {
			logrus.Debugf("Already logged in as %s.", account.Username)
			// Log a successful login event
			loginEvent := event.NewLoginEvent(account.PeerID, account.Username, "Twitter", true, "")
			eventClient.SendLoginEvent(loginEvent)
			return scraper
		}
	}

	RandomSleep()

	if err := scraper.Login(account.Username, account.Password, account.TwoFACode); err != nil {
		logrus.WithError(err).Warnf("Login failed for %s", account.Username)
		// Log a failed login event
		loginEvent := event.NewLoginEvent(account.PeerID, account.Username, "Twitter", false, err.Error())
		eventClient.SendLoginEvent(loginEvent)
		return nil
	}

	RandomSleep()

	if err := SaveCookies(scraper.Scraper, account, cookieDir); err != nil {
		logrus.WithError(err).Errorf("Failed to save cookies for %s", account.Username)
	}

	logrus.Debugf("Login successful for %s", account.Username)
	// Log a successful login event
	loginEvent := event.NewLoginEvent(account.PeerID, account.Username, "Twitter", true, "")
	eventClient.SendLoginEvent(loginEvent)

	return scraper
}
```


Right now, there is no access to the EventClient from this method. Based on the rest of the code we are always using the default configuration for the event client. It might be helpful to add a function to the event package like `GetDefaultEventClient`. 

Because login isn't called often, I don't see an issue with creating a new event client to work with in the auth.go file.

I think there is a better way to do this, but for the sake of speed, I think the above idea is acceptable.

**Comment by mudler** [comment]
We have the follow-ups for implementations #653 #654 . Closing the spike
